version: '3'

services:
  jupyter_service:
    build: .
    entrypoint: "scripts/docker-entrypoint.sh"
    user: root
    ports:
      - 8085:8085
    env_file:
      - .env
    volumes:
      - .:/home/src
