[tool.pdm]

[project]
name = "project"
version = "0.1.0"
description = ""
authors = [
    {name = "", email = ""},
]
dependencies = []
requires-python = ">=3.8"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["pdm-pep517>=1.0"]
build-backend = "pdm.pep517.api"
